export default [
  'yellow lighten-4',
  'deep-orange lighten-4',
  'red lighten-4',
  'green lighten-4',
  'orange lighten-4',
  'blue lighten-4',
  'amber lighten-4',
  'indigo lighten-4',
  'pink lighten-4',
  'light-blue lighten-4',
  'lime lighten-4',
  'cyan lighten-4',
  'light-green lighten-4',
  'teal lighten-4',
  'deep-purple lighten-4',
  'purple lighten-4',
  'brown lighten-4',
  'blue-grey lighten-4',
  'grey lighten-4'
]
