# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Commit File
        uses: actions/checkout@v2

      - name: ADMIN
        uses: actions/checkout@v2
        with:
          repository: innerken-gmbh/aaden-vue-admin
          token: ${{ secrets.PT }}
          path: admin
          ref: emBeded

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x


      - run: |
          cd admin
          npm ci
          npm run admin-build
          cd dist
          echo 'DIST'
          ls
          cd ..
          echo 'MAIN'
          ls
      - run: ls
#    - run: npm run release --if-present
