# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release App To Snap Store

on:
  release:
    types:  [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Commit File
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm install
      - run: npm run release

