# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release App To Github

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Commit File
        uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: ${{ steps.tagName.outputs.tag }}
          draft: true
          prerelease: false
      - run: npm install
      - run: npm run win:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
